import Link from "next/link";
import { Sparkles, ArrowLeft } from "lucide-react";
import Image from "next/image";

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="min-h-screen grid grid-cols-1 lg:grid-cols-2 bg-black overflow-hidden font-geist">
      {/* Left Side: Industrial Aesthetic & Branding */}
      <div className="relative hidden lg:flex flex-col p-12 overflow-hidden border-r border-white/5">
        {/* Background Effects */}
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,rgba(255,107,0,0.08),transparent_50%)] pointer-events-none" />
        <div
          className="absolute inset-0 opacity-20"
          style={{
            backgroundImage: `
              linear-gradient(to right, rgba(255,255,255,0.05) 1px, transparent 1px),
              linear-gradient(to bottom, rgba(255,255,255,0.05) 1px, transparent 1px)
            `,
            backgroundSize: "40px 40px",
          }}
        />

        {/* Top: Back Button */}
        <div className="relative z-10">
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-[10px] uppercase tracking-widest text-white/40 hover:text-[#FF6B00] transition-colors group font-mono"
          >
            <ArrowLeft
              size={12}
              className="group-hover:-translate-x-1 transition-transform"
            />
            Back to Site
          </Link>
        </div>

        {/* Center: Content */}
        <div className="flex-1 flex flex-col justify-center">
          <div className="relative z-10 max-w-md">
            <h2 className="text-4xl font-light text-white leading-tight mb-6">
              The future of CAD <br />
              <span className="text-white/40">is generated by prompt.</span>
            </h2>
            <p className="text-white/40 text-sm leading-relaxed mb-12">
              Accelerate your engineering workflow with Voxen&apos;s generative
              assembly platform. From conceptual block models to production
              schematics in seconds.
            </p>

            <div className="grid grid-cols-2 gap-8 pt-12 border-t border-white/5">
              <div>
                <p className="text-[10px] uppercase tracking-[0.2em] text-[#FF6B00] mb-2 font-mono">
                  Precision
                </p>
                <p className="text-white/60 text-xs leading-relaxed">
                  Assembly-aware generation with physical constraints.
                </p>
              </div>
              <div>
                <p className="text-[10px] uppercase tracking-[0.2em] text-[#FF6B00] mb-2 font-mono">
                  Performance
                </p>
                <p className="text-white/60 text-xs leading-relaxed">
                  Powered by AMD MI300X enterprise acceleration.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="flex items-center justify-center p-8 bg-[#050505] relative">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_80%,rgba(255,107,0,0.03),transparent_50%)] pointer-events-none" />

        <div className="w-full max-w-md relative z-10">{children}</div>
      </div>
    </div>
  );
}
