import { z } from 'zod';

// [REQUIRED] AssemblySchema (Zod)
// What: Validation schema for the 3D assembly JSON generated by the AI
// Where: src/lib/schemas/assembly.ts

export const PartSchema = z.object({
  id: z.string(),
  name: z.string(),
  shape: z.enum(['box', 'sphere', 'cylinder', 'cone', 'plane']),
  position: z.tuple([z.number(), z.number(), z.number()]),
  rotation: z.tuple([z.number(), z.number(), z.number()]),
  scale: z.tuple([z.number(), z.number(), z.number()]),
  color: z.string().regex(/^#[0-9A-Fa-f]{6}$/, 'Must be a valid hex color'),
  geometry: z.object({
    type: z.enum(['box', 'cylinder', 'sphere']),
    dimensions: z.object({
      width: z.number().positive(),
      height: z.number().positive(),
      depth: z.number().positive(),
    }),
  }),
  material: z.object({
    name: z.string(),
    description: z.string(),
  }),
  designIntent: z.string(),
});

export const AssemblyMetadataSchema = z.object({
  generatedAt: z.string().datetime(),
  promptSummary: z.string(),
});

export const AssemblySchema = z.object({
  assemblyName: z.string(),
  version: z.string(),
  parts: z.array(PartSchema).min(1, 'Assembly must have at least one part'),
  metadata: AssemblyMetadataSchema,
});
